parameters:
    #data
    all_data: False
    combine_val: True
    data: cifar10
    num_tasks: 5
    fixed_order: True
    #train
    disp_freq_train: 200
    optimizer: GD
    train_scheme: full
    seperate: False
    random_seed: 0
    num_runs: 15
    epoch: 1
    batch: 10
    #model
    model: GSS_Greedy
    head: single
    arch: resnet18_s
    multi_label: False
    pretrained: False
    num_iter_batch: 1
    mem_size: 100
    eps_mem_batch: 10
    balanced_sampling: False
    num_sample_grad: 10
    #neptune
    learning_rate: 0.1





