parameters:
    #data
    all_data: False
    combine_val: True
    data: cifar10
    num_tasks: 1
    fixed_order: True
    #train
    disp_freq_train: 1000
    optimizer: GD
    train_scheme: full
    seperate: False
    random_seed: 0
    num_runs: 15
    epoch: 5
    batch: 10
    #model
    model: Tiny
    head: single
    arch: resnet18_s
    multi_label: False
    pretrained: False
    num_iter_batch: 1
    mem_size: 1
    eps_mem_batch: 0
    balanced_sampling: False
    is_mir: False
    #neptune
    learning_rate: 0.1





